name: test-run-without-initialization
on:
  workflow_dispatch:
    branches:
      - main
  create:
    branches:
      - main
jobs:
  run-on-clone:
    runs-on: ubuntu-latest
    steps:
      - run: echo HELLO YGGDRASIL
